name: Markdown

on:
  push:

jobs:
  dead-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.4
        with:
          args: "--verbose  --no-progress --cache src/"
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
